'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(__dirname, '..');
const rel = p => path.join(root,p);
const read = p => fs.readFileSync(rel(p),'utf8');
const hash = p => crypto.createHash('sha256').update(fs.readFileSync(rel(p))).digest('hex');
const Model = require(rel('shared/local-data-model.js'));
const Directory = require(rel('shared/local-directory.js'));
const Merchant = require(rel('shared/local-merchant.js'));
const catalog = JSON.parse(read('local/data/catalog.json'));
const launch = JSON.parse(read('local/pilot/pilot-launch.json'));
const qrManifest = JSON.parse(read('local/pilot/stevies-qr-campaigns.json'));
const contract = JSON.parse(read('LOCAL1_9_PILOT_LAUNCH_CONTRACT.json'));
const release18 = JSON.parse(read('LOCAL1_8_RELEASE_CERTIFICATION.json'));
const checks=[]; function check(name,cond){checks.push({name,passed:Boolean(cond)}); assert(cond,name);}
const required=['SPRINT-408-LOCAL-1.9.md','LOCAL1_9_PILOT_LAUNCH_CONTRACT.json','local/pilot/pilot-launch.json','local/pilot/stevies-qr-campaigns.json','local/pilot/STEVIES-STAFF-REDEMPTION-GUIDE.md','local/pilot/PILOT-LAUNCH-RUNBOOK.md','local/pilot/STEVIES-IDENTITY-VALIDATION.md','local/assets/pilot/stevies/qr-table.png','local/assets/pilot/stevies/qr-table.svg','local/assets/pilot/stevies/qr-counter.png','local/assets/pilot/stevies/qr-counter.svg','local/assets/pilot/stevies/qr-placard.png','local/assets/pilot/stevies/qr-placard.svg','local/assets/pilot/stevies/stevies-local-perk-placard.svg'];
required.forEach(p=>check(`required ${p}`,fs.existsSync(rel(p))));
check('catalog schema version preserved',catalog.schema_version==='408-local-merchant-v1');
check('catalog dataset advanced to 1.9',catalog.dataset_version==='408-LOCAL-1.9');
check('catalog validates',Model.validateCatalog(catalog).length===0);
const real=catalog.merchants.filter(m=>m.fixture!==true);
const realPerks=catalog.perks.filter(p=>p.fixture!==true);
check('exactly one real merchant active in candidate',real.length===1 && real[0].status==='active');
check('real merchant is Stevies',real[0].merchant_id==='stevies-bar-grill-sj' && real[0].slug==='stevies-bar-grill');
check('Stevies has expected public address',real[0].address_display==='2705 Union Ave, San Jose, CA 95124');
check('Stevies official website uses https',real[0].website_url==='https://www.steviesbargrill.com/');
check('Stevies instagram configured',real[0].instagram_url==='https://www.instagram.com/stevies_bar/');
check('Stevies is featured Eat Drink',real[0].category==='eat-drink' && real[0].featured===true);
check('exactly one real active perk',realPerks.length===1 && realPerks[0].status==='active');
check('Stevies perk joined to merchant',realPerks[0].merchant_id==='stevies-bar-grill-sj');
check('Stevies perk exact offer',realPerks[0].headline==='20% off food + non-alcoholic drinks');
check('perk is evergreen show screen',realPerks[0].evergreen===true && realPerks[0].redemption_method==='show_screen');
check('perk carries independent offer rule',realPerks[0].independent_offer_text.includes('No insurance purchase or quote required.'));
check('perk terms carry no insurance rule',realPerks[0].terms.includes('No insurance purchase or quote required.'));
const fixtures=catalog.merchants.filter(m=>m.fixture===true), fixturePerks=catalog.perks.filter(p=>p.fixture===true);
check('three original fixture merchants retained',fixtures.length===3);
check('all fixture merchants remain non-public',fixtures.every(m=>m.status==='draft'));
check('three original fixture perks retained',fixturePerks.length===3);
check('all fixture perks remain non-public',fixturePerks.every(p=>p.status==='draft'));
const vms=Model.getMerchantViewModels(catalog,{now:new Date('2026-08-16T12:00:00Z')});
check('public view models expose only one real merchant',vms.length===1);
check('public view model resolves active perk',vms[0].perk && vms[0].perk.perk_id==='stevies-food-na-20');
check('canonical merchant route is correct',vms[0].merchant_url==='/local/stevies-bar-grill/');
const dirHtml=Directory.renderDirectory(vms,'all');
check('directory renderer shows Stevies',dirHtml.includes('Stevie&#39;s Bar &amp; Grill'));
check('directory renderer shows current perk',dirHtml.includes('20% off food + non-alcoholic drinks'));
const detailVm=Merchant.getMerchantDetailViewModel(catalog,'stevies-bar-grill',new Date('2026-08-16T12:00:00Z'));
check('merchant detail resolves Stevies',detailVm && detailVm.merchant.merchant_id==='stevies-bar-grill-sj');
const detailHtml=Merchant.renderMerchantDetail(detailVm);
check('detail renders Use This Perk',detailHtml.includes('Use This Perk'));
check('detail renders no insurance requirement',detailHtml.includes('No insurance purchase or quote required.'));
check('detail includes optional post-value insurance bridge',detailHtml.includes('local-insurance-bridge'));
check('pilot manifest target remains three',launch.target_merchants===3);
check('pilot manifest accurately reports one active',launch.public_merchants_active===1);
check('eat drink slot active',launch.slots.find(s=>s.slot==='eat-drink').status==='active');
check('auto slot intentionally pending',launch.slots.find(s=>s.slot==='auto').status==='pending_recruitment');
check('home slot intentionally pending',launch.slots.find(s=>s.slot==='home').status==='pending_recruitment');
check('auto offer framework stored nonpublicly',launch.slots.find(s=>s.slot==='auto').approved_offer_framework==='10% off services');
check('home offer framework stored nonpublicly',launch.slots.find(s=>s.slot==='home').approved_offer_framework==='15% off services');
check('pending slots cannot activate publicly',launch.slots.filter(s=>s.status==='pending_recruitment').every(s=>s.public_activation_allowed===false));
check('three attributable QR surfaces exist',qrManifest.campaigns.length===3);
for(const c of qrManifest.campaigns){
  const u=new URL(c.url);
  check(`${c.surface}:host correct`,u.hostname==='408farmers.com');
  check(`${c.surface}:canonical path`,u.pathname==='/local/stevies-bar-grill/');
  check(`${c.surface}:source local`,u.searchParams.get('source')==='local');
  check(`${c.surface}:partner id`,u.searchParams.get('partner_id')==='stevies-bar-grill-sj');
  check(`${c.surface}:perk id`,u.searchParams.get('perk_id')==='stevies-food-na-20');
  check(`${c.surface}:merchant slug`,u.searchParams.get('merchant_slug')==='stevies-bar-grill');
  check(`${c.surface}:surface preserved`,u.searchParams.get('surface')===c.surface);
  check(`${c.surface}:utm medium merchant qr`,u.searchParams.get('utm_medium')==='merchant_qr');
  check(`${c.surface}:png exists`,fs.existsSync(rel(c.png.replace(/^\//,''))));
  check(`${c.surface}:svg exists`,fs.existsSync(rel(c.svg.replace(/^\//,''))));
}
const guide=read('local/pilot/STEVIES-STAFF-REDEMPTION-GUIDE.md');
check('staff guide states exact perk',guide.includes('20% off food and non-alcoholic drinks'));
check('staff guide forbids insurance gate',guide.includes('Do not ask the customer to request an insurance quote'));
const placard=read('local/assets/pilot/stevies/stevies-local-perk-placard.svg');
check('placard has exact perk',placard.includes('20% off food + non-alcoholic drinks'));
check('placard has no insurance requirement',placard.includes('No insurance purchase or quote required.'));
check('placard references attributable QR',placard.includes('qr-placard.svg'));
check('1.9 contract reports one of three active',contract.target_merchants===3 && contract.active_real_merchants===1);
check('1.9 contract does not falsely claim operational closeout',contract.release_state==='pilot_launch_candidate_operationally_open');
check('1.9 contract preserves insurance boundary',Object.values(contract.insuranceBoundary).every(v=>v===false));
check('1.9 contract advances only after operational closeout',contract.nextSprintAfterOperationalCloseout==='408-LOCAL-1.10');
check('local directory marker advanced',read('local/index.html').includes('data-local-build="408-LOCAL-1.9"'));
check('local detail marker advanced',read('local/detail/index.html').includes('data-local-build="408-LOCAL-1.9"'));
check('roadmap names current candidate',read('408-LOCAL-ROADMAP.md').includes('408-LOCAL-1.9-PILOT-LAUNCH-CANDIDATE'));
check('roadmap does not mark 1.9 complete',!read('408-LOCAL-ROADMAP.md').includes('408-LOCAL-1.9 — Pilot Merchant Launch — COMPLETE'));
check('root roadmap leaves 1.9 open',/\[ \] 408-LOCAL-1\.9 — Pilot Merchant Launch/.test(read('ROADMAP.md')));
check('version identifies candidate',read('VERSION').trim()==='408-LOCAL-1.9-PILOT-LAUNCH-CANDIDATE');
// Frozen runtimes / insurance acquisition behavior must remain bit-identical to 1.8.
const frozen=['home/index.html','auto-bundle/index.html','buyer/index.html','healthcare/index.html','teachers/index.html','tech/index.html','engineers/index.html','life/index.html','shared/script.js','shared/coveragefit-launch.js','shared/local-attribution.js','shared/local-merchant.js','shared/local-directory.js','shared/local-data-model.js','shared/local-join.js','_worker.js','local/data/catalog.schema.json'];
for(const p of frozen){
  const expected=release18.preservedCoreHashes[p] || release18.sourceHashes[p];
  if(expected) check(`${p}:unchanged from 1.8`,hash(p)===expected);
}
const failed=checks.filter(c=>!c.passed); const result={total:checks.length,passed:checks.length-failed.length,failed:failed.length,checks};
fs.writeFileSync(rel('LOCAL1_9_QA.json'),JSON.stringify(result,null,2));
console.log(`408-LOCAL-1.9 QA: ${result.passed}/${result.total} passed`);
