const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'); let pass=0;
function check(n,f){f(); console.log('PASS',n);pass++;} function storage(){const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function runtime(){const window={location:{origin:'https://408farmers.com',search:'',assign(){}},localStorage:storage(),sessionStorage:storage(),crypto:{randomUUID:()=> 'flow12'},dataLayer:[],LANDING_PAGE_CONFIG:{coverageFitTransitionUrl:'https://coveragefit.com/transition/',coverageFitFallbackUrl:'/home#form'},CustomEvent:function(){}}; const document={readyState:'complete',querySelectorAll:()=>[],addEventListener(){},dispatchEvent(){}}; vm.runInContext(read('shared/coveragefit-launch.js'),vm.createContext({window,document,URL,URLSearchParams,Object,Date,Math,console}));return window;}
check('runtime advances',()=>assert.ok(['408-BUY-1.4','408-BUY-1.5','408-CRO-1.1','408-CRO-1.2','408-CRO-1.3','408-CRO-1.4', '408-CRO-1.5', '408-CRO-1.6', '408-CRO-1.6.1', '408-CRO-1.6.2', '408-CRO-1.6.2.1','408-LIFE-1.1','408-LIFE-1.2','408-LIFE-1.3','408-LIFE-1.4','408-LIFE-1.4.1','408-LIFE-1.5','408-LIFE-1.6','408-LIFE-1.7','408-FLOW-1.5','408-HOME-2.1','408-HOME-2.2','408-HOME-2.3','408-HOME-2.4','408-HOME-2.5','408-HOME-2.6','408-HOME-2.7','408-HOME-2.8','408-HOME-2.9','408-FLOW-2.1','408-FLOW-2.2','408-FLOW-2.3','408-FLOW-2.4','408-CF-RPT-1.1','408-FLOW-2.5'].includes(read('VERSION').trim())));
check('homepage explicit start declares assessment next',()=>{const h=read('index.html');assert(h.includes('data-cf-entry="homepage_hero"'));assert(h.includes('data-cf-next="/assessment/"'));});
check('shared launcher consumes declarative cfNext',()=>assert(read('shared/coveragefit-launch.js').includes('next: element.dataset.cfNext || null')));
check('score explicit start supplies assessment next',()=>assert(read('shared/score.js').includes("next:'/assessment/'")));
check('explicit start builds transition to assessment',()=>{const u=new URL(runtime().CoverageFitLauncher.buildUrl({entry:'homepage_hero',next:'/assessment/'}));assert.equal(u.pathname,'/transition/');assert.equal(u.searchParams.get('next'),'/assessment/');});
check('exploratory launcher default remains Home',()=>{const u=new URL(runtime().CoverageFitLauncher.buildUrl({entry:'explore'}));assert.equal(u.searchParams.get('next'),'/home/');});
check('existing form direct-start contract remains',()=>{for(const rel of ['home/index.html','auto-bundle/index.html','buyer/index.html'])assert(read(rel).includes('data-cf-next="/assessment/"'),rel);});
check('no parallel assessment introduced',()=>assert(!fs.existsSync(path.join(root,'score','assessment'))));
console.log(`FLOW-1.2: ${pass} passed, 0 failed`);
