#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(root, rel));
const checks = [];
const check = (name, value) => { assert.ok(value, name); checks.push(name); };

const life = read('life/index.html');
const thanks = read('life/thank-you.html');
const css = read('shared/life.css');
const js = read('shared/life-intake.js');
const manifest = JSON.parse(read('handoff-manifest.json'));

check('runtime preserves LIFE-1.3 contract after secure release', ['408-LIFE-1.3','408-LIFE-1.4','408-LIFE-1.4.1','408-LIFE-1.5','408-LIFE-1.6','408-LIFE-1.7','408-FLOW-1.5','408-HOME-2.1','408-HOME-2.2','408-HOME-2.3','408-HOME-2.4','408-HOME-2.5','408-HOME-2.6','408-HOME-2.7','408-HOME-2.8','408-HOME-2.9','408-FLOW-2.1','408-FLOW-2.2','408-FLOW-2.3','408-FLOW-2.4','408-CF-RPT-1.1','408-FLOW-2.5'].includes(read('VERSION').trim()) && ['408-LIFE-1.3','408-LIFE-1.4','408-LIFE-1.4.1','408-LIFE-1.5','408-LIFE-1.6','408-LIFE-1.7','408-FLOW-1.5','408-HOME-2.1','408-HOME-2.2','408-HOME-2.3','408-HOME-2.4','408-HOME-2.5','408-HOME-2.6','408-HOME-2.7','408-HOME-2.8','408-HOME-2.9','408-FLOW-2.1','408-FLOW-2.2','408-FLOW-2.3','408-FLOW-2.4','408-CF-RPT-1.1','408-FLOW-2.5'].includes(manifest.runtime));
for (const rel of ['life/index.html','life/thank-you.html','shared/life.css','shared/life-intake.js','SPRINT-408-LIFE-1.3.md']) check(`exists:${rel}`, exists(rel));
check('life surfaces carry LIFE-1.3+ build', /data-life-build="408-LIFE-1\.[34567](?:\.\d+)?"/.test(life) && /data-life-build="408-LIFE-1\.[34567](?:\.\d+)?"/.test(thanks));
check('three approved engagement questions remain', ['What would you most want life insurance to protect?','If something happened to you, how long could your household comfortably continue without your income?','What life insurance do you already have today?'].every(text => life.includes(text)));
check('application intro creates deliberate phase boundary', life.includes('data-life-application-intro') && life.includes("Let's get your application ready.") && life.includes('data-life-application-start'));
check('six total progressive fieldsets exist', (life.match(/data-life-step="[1-6]"/g) || []).length === 6);
check('exactly three application fieldsets exist', (life.match(/data-life-phase="application"/g) || []).length === 3);
check('legal-name fields exist', ['first_name','middle_name','last_name'].every(name => life.includes(`name="${name}"`)));
check('gender field exists with bounded paths', (life.match(/name="gender"/g) || []).length === 3 && ['female','male','discuss'].every(value => life.includes(`name="gender" value="${value}"`)));
check('DOB field exists', life.includes('name="date_of_birth"') && life.includes('data-life-dob'));
check('structured residential address exists', ['residential_address','residential_address_2','residential_city','residential_state','residential_zip'].every(name => life.includes(`name="${name}"`)));
check('email is required application field', life.includes('type="email" name="email"') && life.includes('data-life-email'));
check('mobile is optional', life.includes('type="tel" name="phone"') && !/type="tel" name="phone"[^>]*required/.test(life));
check('last4 field is present and masked', life.includes('type="password" name="ssn_last4"') && life.includes('maxlength="4"') && life.includes('data-life-ssn-last4'));
check('last4 disables autocomplete', /name="ssn_last4"[^>]*autocomplete="off"/.test(life));
check('application acknowledgement exists', life.includes('name="application_acknowledgement"') && life.includes('data-life-application-ack'));
check('application fields are disabled by default until JS phase entry', (life.match(/<input disabled /g) || []).length >= 14 && js.includes('function setApplicationFieldsEnabled') && js.includes('setApplicationFieldsEnabled(true)'));
check('no-js path warns against entering application identity data', life.includes('<noscript>') && life.includes('do not enter application identity information below'));
check('secure submit is absent before 1.4 or isolated to dedicated control later', !/type="submit"/i.test(life) || life.includes('data-life-secure-submit'));
check('life script performs no network submission', !/fetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket|formspree/i.test(js));
check('life script uses no persistent browser storage', !/localStorage|sessionStorage|indexedDB|document\.cookie/i.test(js));
check('life script does not serialize applicant payload', !/new\s+FormData|JSON\.stringify\s*\(\s*(?:form|payload|applicant)/i.test(js));
check('life script does not write application data to URL', !/(ssn_last4|date_of_birth|residential_address|first_name|email).*replaceState/i.test(js));
check('progress events remain answer-free', js.includes("'life:intake-progress'") && js.includes('detail: { step: step, phase: phase, completed: !!completed, build: BUILD }'));
check('DOB local validation is bounded', js.includes('validDateOfBirth') && js.includes('now.getFullYear() - 120') && js.includes('dob >= now'));
check('ZIP and optional phone local validation exist', js.includes('validZip') && js.includes('validPhone'));
check('last4 validation is exactly four digits', js.includes('function validLast4') && js.includes('/^\\d{4}$/'));
check('application fields have an explicit clear path', js.includes('function clearApplicationFields') && (js.includes('finishLocalValidation') || js.includes('finishSecureSubmission')));
check('application fields are cleared on pagehide and bfcache restore', js.includes("window.addEventListener('pagehide', function ()") && js.includes('event.persisted') && js.includes('clearApplicationFields()') && js.includes('setApplicationFieldsEnabled(false)'));
check('application completion language matches current boundary', (life.includes('Nothing was submitted online.') && life.includes('application-detail fields have been cleared')) || life.includes('application-start details were received'));
check('direct Dylan fallback remains', life.includes('../contact/?intent=life') && (life.includes('Continue with Dylan now') || life.includes('Questions? Contact Dylan')));
check('no health or medical underwriting questions added', !/name="[^"]*(?:health|medical|diagnos|prescription|tobacco)[^"]*"/i.test(life));
check('CoverageFit runtime remains outside life intake', !/coveragefit-launch\.js|CoverageFitLauncher|coveragefit-launch/i.test(life) && !/CoverageFitLauncher|coveragefit-launch/i.test(js));
check('life CSS includes application, sensitive, mobile and forced-colors states', css.includes('.life-field-grid') && css.includes('.life-sensitive-card') && css.includes('@media(max-width:760px)') && css.includes('@media(forced-colors:active)'));
check('manifest publishes application initialization contract', ['408-LIFE-1.3','408-LIFE-1.4','408-LIFE-1.4.1','408-LIFE-1.5','408-LIFE-1.6','408-LIFE-1.7','408-FLOW-1.5','408-HOME-2.1','408-HOME-2.2','408-HOME-2.3','408-HOME-2.4','408-HOME-2.5','408-HOME-2.6','408-HOME-2.7','408-HOME-2.8','408-HOME-2.9','408-FLOW-2.1','408-FLOW-2.2','408-FLOW-2.3','408-FLOW-2.4','408-CF-RPT-1.1','408-FLOW-2.5'].includes(manifest.lifeCampaignFoundation?.build) && manifest.lifeCampaignFoundation?.applicationInitializationEnabled === true);
check('manifest marks sensitive UI with no browser persistence', manifest.lifeCampaignFoundation?.sensitiveCollectionEnabled === true && (manifest.lifeCampaignFoundation?.producerQueueBrowserPersistence === false || manifest.lifeCampaignFoundation?.sensitivePersistenceEnabled === false));
check('manifest keeps ordinary lead submission separate', manifest.lifeCampaignFoundation?.formSubmissionEnabled === false || manifest.lifeCampaignFoundation?.secureSubmissionBoundaryEnabled === true);
check('manifest preserves paid-traffic lifecycle through final certification', manifest.lifeCampaignFoundation?.build==='408-LIFE-1.7' ? manifest.lifeCampaignFoundation?.paidTrafficReady===true : (manifest.lifeCampaignFoundation?.paidTrafficReady===false && /408-LIFE-1\.[4567]/.test(manifest.lifeCampaignFoundation?.paidTrafficGate || '')));
check('manifest points to next LIFE sprint or completes sequence', manifest.lifeCampaignFoundation?.build==='408-LIFE-1.7' ? manifest.lifeCampaignFoundation?.nextSprint===null : ['408-LIFE-1.4','408-LIFE-1.5','408-LIFE-1.6','408-LIFE-1.7','408-FLOW-1.5','408-HOME-2.1','408-HOME-2.2','408-HOME-2.3','408-HOME-2.4','408-HOME-2.5','408-HOME-2.6','408-HOME-2.7','408-HOME-2.8','408-HOME-2.9','408-FLOW-2.1','408-FLOW-2.2','408-FLOW-2.3','408-FLOW-2.4','408-CF-RPT-1.1','408-FLOW-2.5'].includes(manifest.lifeCampaignFoundation?.nextSprint));
check('CoverageFit seven-route contract remains unchanged', Array.isArray(manifest.routes) && manifest.routes.length === 7 && manifest.coverageFit?.zeroRepeat === true);
check('existing Formspree path remains unchanged', manifest.formspree?.host === 'formspree.io' && manifest.formspree?.path === '/f/mojgnegn');

console.log(JSON.stringify({ sprint: '408-LIFE-1.3', passed: checks.length, failed: 0, checks }, null, 2));
